title: "" # name of the site
author: Sadamori Kojaku # name of site's author
email: skojaku@binghamton.edu # email of site's author
url: https://skojaku.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Welcome! This is Sadamori Kojaku's personal webpage.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please
#theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

# Markdown configuration
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections configuration
collections_dir: content/blog
collections:
  posts:
    output: true
    permalink: /:slug.html

# Include content pages for processing
include:
  - content/pages

# Include static files from post bundles
defaults:
  - scope:
      path: "content/blog/_posts"
    values:
      layout: "post"

# Process images and assets within post folders
include:
  - content/blog/_posts/**/*.png
  - content/blog/_posts/**/*.jpg
  - content/blog/_posts/**/*.jpeg
  - content/blog/_posts/**/*.gif
  - content/blog/_posts/**/*.svg

plugins:
  - jekyll-feed
  - jekyll-seo-tag
